### ISSUE TITLE
How to use Dat3M with the given examples

### ISSUE THREAD

**Issue by wiggleman** [hernanponcedeleon/Dat3M#790] opened 2024-12-12 21:16 UTC
I imported the given example at `litmus/ptr/CADP/2_threads_2_instructions/0_simple.litmus`. I configured the tool to target PTX, with lazy analysis and Z3 solver, please refer to the screenshot for the specific setting. There's a popup with the shown error. Could you please explain how the examples are used, or if I need to install other dependencies?

![截屏2024-12-12 22 08 35](https://github.com/user-attachments/assets/474fe4c2-efa1-4ba0-bbbc-279ff2833084)

**Comment by ThomasHaas** [comment] 2024-12-12 21:34
You also need to import a `.cat` file from the `cat/` directory.
The error you see comes from the parser because there is no memory model (the second panel in your screenshot).
In your case, you need to import `cat/ptx-v6.0.cat` or `cat/ptx-v7.5.cat`

**Comment by ThomasHaas** [comment] 2024-12-17 23:53
Could you get it to work?

**Comment by wiggleman** [comment] 2024-12-18 07:35
Hello Mr.Haas,

Yes! Thanks for the follow up. My colleague did get it to work. But when I try my installation, with both the test and Target Memory Model imported. It reports: “error parsing stdlib.cat file”. Do you happen to have an idea what’s causing it? 

Thanks a lot!

Best,
Boran 

> 2024年12月18日 00:53，Thomas Haas ***@***.***> 写道：
> 
>

**Comment by hernanponcedeleon** [comment] 2024-12-18 08:22
Do you have the `DAT3M_HOME` env variable set as described in the README?
```
export DAT3M_HOME=<Dat3M's root>
export DAT3M_OUTPUT=$DAT3M_HOME/output
```

**Comment by wiggleman** [comment] 2024-12-18 08:34
Hi,

That’s indeed the problem! Thanks a lot, and thank you for providing this amazing application, it really helps with our project in Formal Verification.

Best,
Boran

2024年12月18日 09:22，Hernan Ponce de Leon ***@***.***> 写道：



Do you have the DAT3M_HOME env variable set as described in the README?

export DAT3M_HOME=<Dat3M's root>
export DAT3M_OUTPUT=$DAT3M_HOME/output

**Comment by hernanponcedeleon** [comment] 2024-12-18 08:36
Happy to hear the problem is solved (thus I am closing this issue) and that you enjoy the tool.

If you encounter more problems, let's us know.

**Closed by hernanponcedeleon** 2024-12-18 08:36 UTC

**Comment by ThomasHaas** [comment] 2024-12-18 21:47
Yes, this is intended for now. The reason is that these `exists/forall` clauses specify _final_ register/memory values, i.e., values at the end of the execution. So we only evaluate these clauses on _terminating_ executions and ignore them for all non-terminating one's.
If you care about termination, you can change the property to check for to `liveness` (for your code, Dartagnan will report a liveness issue).
