### ISSUE TITLE
N-ary Relations

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#71] opened 2021-07-03 10:37 UTC
Problem: We only have binary unions, intersections and compositions.

N-ary relations (especially unions, which are very common) could be handled more efficiently than nested unions.

**Comment by hernanponcedeleon** [comment] 2021-08-06 17:26
I did the first changes to convert binary relations to n-ary ones during parsing.

However, the `encodeTupleSet` is `null` during the a
`addEncodeTupleSet`.

I think the problem is related to recursive relations and we might need to do something like in binary relations using `lastEncodingIteration`.

**Comment by hernanponcedeleon** [comment] 2021-08-16 13:53
I did some progress about this. The relations are correctly (all test pass) merged during the parsing.
However we still populate the `RelationRepository` with intermediate relations, e.g. for `r1+r2+r3` the repository will contain `r1+r2` and `r1+r2+r3` (on top of the "singleton" ones).
Avoiding the intermediate ones is not trivial because they might be used somewhere else, e.g. in
```
let r = r1+r2
acyclic(r)
empty(r1+r2+r3)
```
we cannot blindly remove `r1+r2`. 

I have yet no clue how we could detect the cases where we can remove "intermediate" ones and when not. Before going down that road, it might make sense to test if as we expected we obtain a performance boost due to the use of nary relations.

During the parsing I avoid the merging if the relation is a `RelMinus` (not associative) or `RelComposition` (this one is associative but if I understand correctly, this would be the case tackled by #72, right @ThomasHaas ?)

**Comment by ThomasHaas** [comment] 2021-08-16 14:14
I think I mentioned this before, but you would simply never merge relations if they are named. E.g. in your case, ```r=r1+r2``` is a named relation, so an instance of ```(r1+r2)+r3``` should be treated as ```r + r3```which is binary and hence not mergable. On the other hand, ```r1 + (r2 + r3)``` would be mergable into a ternary union.
In most cases a relation is named because it is reused multiple times, so the naming already provides a solid grouping of relations, so I would treat them similarly to a base relation in this context. Ideally, you would explore the dependency graph of the CAT WMM to see which mergings can be performed (if ```(r1+r2)``` has a single dependent ```(r1+r2)+r3```, you could perform merging, if it has multiple you don't). The WMM class already has a method to retrieve the dependency graph.

I think the benefit of merging has more to do with commutativity rather than associativity. It is true that RelComposition could be merged, but every composed relation has to be treated differently depending on its position inside the composition chain, which somewhat negates the benefit of merging them (you need to be able to identify the pre-composed relations and the post-composed relations, which effectively causes a splitting again). And yes, it would be tackled by #72. However, to apply #72 you still need to identify a chain of compositions but instead of merging them, you re-pair the binary composition in a different order. So if you have code that can identify such chains, we can reuse that for #72.

**Comment by hernanponcedeleon** [comment] 2023-01-25 19:43
We do have full support to this now, right? If so, this can be closed

**Closed** 2023-05-16 19:52 UTC
Labels: enhancement
